### ISSUE TITLE
驱动器控制程序集成到RTDE

### ISSUE THREAD

**Issue by likecanyon** [rocos-sia/UR_RTDE_Examples#1]
只靠定义一个sendbuffer和serialPort.writesome控制不了驱动器呀，这是怎么回事儿呢？求教师兄！

**Comment by xiao-xiao-jiang** [comment]
`sizeof()`使用不当的问题

**Comment by xiao-xiao-jiang** [comment]
> 只靠定义一个sendbuffer和serialPort.writesome控制不了驱动器呀，这是怎么回事儿呢？求教师兄！

`sizeof`使用不当问题
